export const styles: { [key: string]: React.CSSProperties } = {
        overlay: {
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            // Overlay blanco con degradé suave semi-transparente
            background: 'linear-gradient(135deg, rgba(255, 255, 255, 0.85) 0%, rgba(243, 244, 246, 0.95) 100%)',
            backdropFilter: 'blur(8px)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 1000,
            padding: '1rem',
        },
        modalCard: {
            position: 'relative',
            backgroundColor: '#ffffff',
            borderRadius: '1rem',
            padding: '2rem',
            width: '100%',
            maxWidth: '420px',
            boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)',
            border: '1px solid #f3f4f6',
            fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
        },
        closeButton: {
            position: 'absolute',
            top: '1rem',
            right: '1rem',
            background: 'transparent',
            border: 'none',
            fontSize: '1.25rem',
            color: '#9ca3af',
            cursor: 'pointer',
            padding: '0.25rem 0.5rem',
            borderRadius: '0.375rem',
        },
        title: {
            margin: '0 0 1.5rem 0',
            fontSize: '1.5rem',
            fontWeight: 700,
            color: '#111827',
        },
        form: {
            display: 'flex',
            flexDirection: 'column',
            gap: '1.25rem',
        },
        inputGroup: {
            display: 'flex',
            flexDirection: 'column',
            gap: '0.375rem',
        },
        label: {
            fontSize: '0.875rem',
            fontWeight: 500,
            color: '#374151',
        },
        input: {
            width: '100%',
            padding: '0.75rem 1rem',
            fontSize: '1rem',
            borderRadius: '0.5rem',
            border: '1px solid #d1d5db',
            outline: 'none',
            boxSizing: 'border-box',
            color: '#111827',
            transition: 'border-color 0.2s, box-shadow 0.2s',
        },
        inputError: {
            borderColor: '#ef4444',
            boxShadow: '0 0 0 1px #ef4444',
        },
        alertText: {
            fontSize: '0.8125rem',
            color: '#dc2626',
            marginTop: '0.25rem',
        },
        submitBtn: {
            width: '100%',
            padding: '0.75rem 1.5rem',
            fontSize: '1rem',
            fontWeight: 600,
            color: '#ffffff',
            backgroundColor: '#2563eb', // Azul estilo Tailwind
            border: 'none',
            borderRadius: '0.5rem',
            cursor: 'pointer',
            transition: 'background-color 0.2s, opacity 0.2s',
        },
        submitBtnDisabled: {
            backgroundColor: '#9ca3af',
            cursor: 'not-allowed',
            opacity: 0.6,
        },
    };